name: RH

services:
  site:
    build:
      context: ./FrontEnd/site
      dockerfile: Dockerfile
    image: marketplace-site
    container_name: marketplace-site
    ports:
      - "8081:80"
    restart: unless-stopped

  admin:
    build:
      context: ./FrontEnd/admin
      dockerfile: Dockerfile
    image: marketplace-admin
    container_name: marketplace-admin
    ports:
      - "8082:80"
    restart: unless-stopped

  client:
    build:
      context: ./FrontEnd/client
      dockerfile: Dockerfile
    image: marketplace-client
    container_name: marketplace-client
    ports:
      - "8083:80"
    restart: unless-stopped

  lawyers:
    build:
      context: ./FrontEnd/lawyers
      dockerfile: Dockerfile
    image: marketplace-lawyers
    container_name: marketplace-lawyers
    ports:
      - "8084:80"
    restart: unless-stopped